/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.UserRole;

import Business.Doctor.Doctor;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.City.City;
import Business.Organization.Organization;
import Business.PatientManager.PatientManager;
import Business.Person.PersonalNotification;
import Business.RegisteredUser.RegisteredUser;
import Business.UserAccount.UserAccount;
import Business.WorkProcess.HealthRequest;
import UI.DoctorRole.AddPrescription;
import UI.DoctorRole.AssignHospitalToRequest;
import UI.DoctorRole.ViewPrescriptionJPanel;
import UI.TestingServiceRole.CompletedTestReport;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jazibjavaid
 */
public class HealthRequestReport extends javax.swing.JPanel {

    /**
     * Creates new form ManageProfileJPanel
     */
    private ArrayList<String> comorbid;
    private UserAccount useraccount;
    private EcoSystem system;
    private HealthRequest request;
    private JPanel userProcessContainer;
    private PatientManager patientManager;
    private String buttonFlag;
    private Enterprise enterprise;
    private Organization org;
    DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");

    public HealthRequestReport(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, EcoSystem system, HealthRequest request, PatientManager patientManager, String buttonFlag, Organization org) {
        initComponents();
        this.useraccount = account;
        this.system = system;
        this.request = request;
        this.enterprise = enterprise;
        this.org = org;
        this.userProcessContainer = userProcessContainer;
        this.patientManager = patientManager;
        this.buttonFlag = buttonFlag;
        btnPres.setVisible(false);
        btnBed.setVisible(false);
        btnTest.setVisible(false);
        doctorJpanel.setVisible(false);
        toggleActionButtons();
        //togglePrescriptionButton();
        toggleButton();
        toggleDoctorButton();
        populateprofile();
        toggleAllButtons();
        toggleBTAMButtons();
        this.comorbid = new ArrayList<>();
        doctorJTable.setRowHeight(25);
        doctorJTable.getTableHeader().setDefaultRenderer(new HeaderColor());

    }

    public class HeaderColor extends DefaultTableCellRenderer {

        public HeaderColor() {
            setOpaque(true);
        }

        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);
            setBackground(new java.awt.Color(253, 217, 208));
            return this;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        lblContactNo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblContactNo1 = new javax.swing.JLabel();
        lblRequestNumber = new javax.swing.JLabel();
        lblPatientsName = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        viewAvailableTest = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblPatientManagerName = new javax.swing.JLabel();
        lblZipCode1 = new javax.swing.JLabel();
        lblDoctorsName = new javax.swing.JLabel();
        lblContactNo2 = new javax.swing.JLabel();
        lblNursesName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblHospitalsName = new javax.swing.JLabel();
        lblContactNo3 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnViewPresc = new javax.swing.JButton();
        btnAssignToMe = new javax.swing.JButton();
        btnAssignToDoctor = new javax.swing.JButton();
        doctorJpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorJTable = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        btnPres = new javax.swing.JButton();
        btnBed = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        btnReportBacktoAM = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblDob1 = new javax.swing.JLabel();
        lblFever = new javax.swing.JLabel();
        jPanelGender = new javax.swing.JPanel();
        lblGender1 = new javax.swing.JLabel();
        lblBodyPain = new javax.swing.JLabel();
        jPanelGender1 = new javax.swing.JPanel();
        lblGender2 = new javax.swing.JLabel();
        lblCough = new javax.swing.JLabel();
        jPanelGender2 = new javax.swing.JPanel();
        lblGender3 = new javax.swing.JLabel();
        lblOtherSymptoms = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1039, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(217, 217, 217));

        jLabel2.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        jLabel2.setText("Request Number:");

        lblZipCode.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblZipCode.setText("Patients Name:");

        lblContactNo.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblContactNo.setText("Contact Number:");

        jLabel1.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        jLabel1.setText("Gender:");

        lblContactNo1.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblContactNo1.setText("Date of Birth");

        lblRequestNumber.setBackground(new java.awt.Color(255, 255, 255));
        lblRequestNumber.setText("jLabel4");
        lblRequestNumber.setMaximumSize(new java.awt.Dimension(6, 20));
        lblRequestNumber.setMinimumSize(new java.awt.Dimension(6, 20));
        lblRequestNumber.setPreferredSize(new java.awt.Dimension(6, 20));

        lblPatientsName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientsName.setText("jLabel4");
        lblPatientsName.setMaximumSize(new java.awt.Dimension(6, 20));
        lblPatientsName.setMinimumSize(new java.awt.Dimension(6, 20));
        lblPatientsName.setPreferredSize(new java.awt.Dimension(6, 20));

        lblContact.setBackground(new java.awt.Color(255, 255, 255));
        lblContact.setText("jLabel4");
        lblContact.setMaximumSize(new java.awt.Dimension(6, 20));
        lblContact.setMinimumSize(new java.awt.Dimension(6, 20));
        lblContact.setPreferredSize(new java.awt.Dimension(6, 20));

        lblGender.setBackground(new java.awt.Color(255, 255, 255));
        lblGender.setText("jLabel4");
        lblGender.setMaximumSize(new java.awt.Dimension(6, 20));
        lblGender.setMinimumSize(new java.awt.Dimension(6, 20));
        lblGender.setPreferredSize(new java.awt.Dimension(6, 20));

        lblDob.setBackground(new java.awt.Color(255, 255, 255));
        lblDob.setText("jLabel4");
        lblDob.setMaximumSize(new java.awt.Dimension(6, 20));
        lblDob.setMinimumSize(new java.awt.Dimension(6, 20));
        lblDob.setPreferredSize(new java.awt.Dimension(6, 20));

        jButton1.setBackground(new java.awt.Color(253, 135, 124));
        jButton1.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        jButton1.setText("View complete Profile");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        viewAvailableTest.setBackground(new java.awt.Color(253, 135, 124));
        viewAvailableTest.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        viewAvailableTest.setText("View Available tests");
        viewAvailableTest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewAvailableTest.setContentAreaFilled(false);
        viewAvailableTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAvailableTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAvailableTestMouseExited(evt);
            }
        });
        viewAvailableTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAvailableTestActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        jLabel3.setText("Patient Manager Name:");

        lblPatientManagerName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientManagerName.setText("jLabel4");
        lblPatientManagerName.setMaximumSize(new java.awt.Dimension(6, 20));
        lblPatientManagerName.setMinimumSize(new java.awt.Dimension(6, 20));
        lblPatientManagerName.setPreferredSize(new java.awt.Dimension(6, 20));

        lblZipCode1.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblZipCode1.setText("Doctor's Name:");

        lblDoctorsName.setBackground(new java.awt.Color(255, 255, 255));
        lblDoctorsName.setText("jLabel4");
        lblDoctorsName.setMaximumSize(new java.awt.Dimension(6, 20));
        lblDoctorsName.setMinimumSize(new java.awt.Dimension(6, 20));
        lblDoctorsName.setPreferredSize(new java.awt.Dimension(6, 20));

        lblContactNo2.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblContactNo2.setText("Nurse's Name:");

        lblNursesName.setBackground(new java.awt.Color(255, 255, 255));
        lblNursesName.setText("jLabel4");
        lblNursesName.setMaximumSize(new java.awt.Dimension(6, 20));
        lblNursesName.setMinimumSize(new java.awt.Dimension(6, 20));
        lblNursesName.setPreferredSize(new java.awt.Dimension(6, 20));

        jLabel4.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        jLabel4.setText("Hospital's Name");

        lblHospitalsName.setBackground(new java.awt.Color(255, 255, 255));
        lblHospitalsName.setText("jLabel4");
        lblHospitalsName.setMaximumSize(new java.awt.Dimension(6, 20));
        lblHospitalsName.setMinimumSize(new java.awt.Dimension(6, 20));
        lblHospitalsName.setPreferredSize(new java.awt.Dimension(6, 20));

        lblContactNo3.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblContactNo3.setText("Status");

        lblStatus.setBackground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("jLabel4");
        lblStatus.setMaximumSize(new java.awt.Dimension(6, 20));
        lblStatus.setMinimumSize(new java.awt.Dimension(6, 20));
        lblStatus.setPreferredSize(new java.awt.Dimension(6, 20));

        btnViewPresc.setBackground(new java.awt.Color(253, 135, 124));
        btnViewPresc.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnViewPresc.setText("View Prescription");
        btnViewPresc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnViewPresc.setContentAreaFilled(false);
        btnViewPresc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPrescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewAvailableTest, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblContactNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblContactNo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblZipCode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblContactNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatientManagerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(lblDoctorsName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNursesName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHospitalsName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblRequestNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(lblPatientsName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblContact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnViewPresc, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRequestNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPatientsName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDoctorsName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPatientManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContactNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNursesName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHospitalsName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAvailableTest, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnViewPresc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        btnAssignToMe.setBackground(new java.awt.Color(253, 135, 124));
        btnAssignToMe.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnAssignToMe.setText("Assign to Me");
        btnAssignToMe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAssignToMe.setContentAreaFilled(false);
        btnAssignToMe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAssignToMeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAssignToMeMouseExited(evt);
            }
        });
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        btnAssignToDoctor.setBackground(new java.awt.Color(253, 135, 124));
        btnAssignToDoctor.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnAssignToDoctor.setText("Assign a Doctor");
        btnAssignToDoctor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAssignToDoctor.setContentAreaFilled(false);
        btnAssignToDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAssignToDoctorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAssignToDoctorMouseExited(evt);
            }
        });
        btnAssignToDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToDoctorActionPerformed(evt);
            }
        });

        doctorJpanel.setBackground(new java.awt.Color(255, 255, 255));

        doctorJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor Name", "Qualification", "Experience", "Zipcode"
            }
        ));
        doctorJTable.setSelectionBackground(new java.awt.Color(217, 217, 217));
        jScrollPane1.setViewportView(doctorJTable);

        btnSubmit.setBackground(new java.awt.Color(253, 135, 124));
        btnSubmit.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/submit.png"))); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSubmit.setContentAreaFilled(false);
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout doctorJpanelLayout = new javax.swing.GroupLayout(doctorJpanel);
        doctorJpanel.setLayout(doctorJpanelLayout);
        doctorJpanelLayout.setHorizontalGroup(
            doctorJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorJpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        doctorJpanelLayout.setVerticalGroup(
            doctorJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnPres.setBackground(new java.awt.Color(253, 135, 124));
        btnPres.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnPres.setText("Add Prescription");
        btnPres.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPres.setContentAreaFilled(false);
        btnPres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPresMouseExited(evt);
            }
        });
        btnPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresActionPerformed(evt);
            }
        });

        btnBed.setBackground(new java.awt.Color(253, 135, 124));
        btnBed.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnBed.setText("Assign Bed");
        btnBed.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBed.setContentAreaFilled(false);
        btnBed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBedMouseExited(evt);
            }
        });
        btnBed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBedActionPerformed(evt);
            }
        });

        btnTest.setBackground(new java.awt.Color(253, 135, 124));
        btnTest.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnTest.setText("Assign Test");
        btnTest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTest.setContentAreaFilled(false);
        btnTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTestMouseExited(evt);
            }
        });
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        btnReportBacktoAM.setBackground(new java.awt.Color(253, 135, 124));
        btnReportBacktoAM.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnReportBacktoAM.setText("Report to Patient Manager");
        btnReportBacktoAM.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnReportBacktoAM.setContentAreaFilled(false);
        btnReportBacktoAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportBacktoAMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportBacktoAMMouseExited(evt);
            }
        });
        btnReportBacktoAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportBacktoAMActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(253, 135, 153));
        jButton2.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(177, 80));

        lblDob1.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblDob1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDob1.setText("Fever");

        lblFever.setBackground(new java.awt.Color(255, 255, 255));
        lblFever.setText("jLabel4");
        lblFever.setMaximumSize(new java.awt.Dimension(6, 20));
        lblFever.setMinimumSize(new java.awt.Dimension(6, 20));
        lblFever.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblDob1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFever, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblDob1)
                .addGap(18, 18, 18)
                .addComponent(lblFever, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanelGender.setBackground(new java.awt.Color(204, 204, 204));
        jPanelGender.setPreferredSize(new java.awt.Dimension(177, 80));

        lblGender1.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblGender1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender1.setText("Body Pain");

        lblBodyPain.setBackground(new java.awt.Color(255, 255, 255));
        lblBodyPain.setText("jLabel4");
        lblBodyPain.setMaximumSize(new java.awt.Dimension(6, 20));
        lblBodyPain.setMinimumSize(new java.awt.Dimension(6, 20));
        lblBodyPain.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanelGenderLayout = new javax.swing.GroupLayout(jPanelGender);
        jPanelGender.setLayout(jPanelGenderLayout);
        jPanelGenderLayout.setHorizontalGroup(
            jPanelGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGenderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(lblBodyPain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelGenderLayout.setVerticalGroup(
            jPanelGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGenderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblGender1)
                .addGap(18, 18, 18)
                .addComponent(lblBodyPain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        jPanelGender1.setBackground(new java.awt.Color(204, 204, 204));
        jPanelGender1.setPreferredSize(new java.awt.Dimension(177, 80));

        lblGender2.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblGender2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender2.setText("Cough");

        lblCough.setBackground(new java.awt.Color(255, 255, 255));
        lblCough.setText("jLabel4");
        lblCough.setMaximumSize(new java.awt.Dimension(6, 20));
        lblCough.setMinimumSize(new java.awt.Dimension(6, 20));
        lblCough.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanelGender1Layout = new javax.swing.GroupLayout(jPanelGender1);
        jPanelGender1.setLayout(jPanelGender1Layout);
        jPanelGender1Layout.setHorizontalGroup(
            jPanelGender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGender1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(lblCough, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelGender1Layout.setVerticalGroup(
            jPanelGender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGender1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblGender2)
                .addGap(18, 18, 18)
                .addComponent(lblCough, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        jPanelGender2.setBackground(new java.awt.Color(204, 204, 204));
        jPanelGender2.setPreferredSize(new java.awt.Dimension(177, 80));

        lblGender3.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblGender3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender3.setText("Other Symptoms");

        lblOtherSymptoms.setBackground(new java.awt.Color(255, 255, 255));
        lblOtherSymptoms.setText("jLabel4");
        lblOtherSymptoms.setMaximumSize(new java.awt.Dimension(6, 20));
        lblOtherSymptoms.setMinimumSize(new java.awt.Dimension(6, 20));
        lblOtherSymptoms.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanelGender2Layout = new javax.swing.GroupLayout(jPanelGender2);
        jPanelGender2.setLayout(jPanelGender2Layout);
        jPanelGender2Layout.setHorizontalGroup(
            jPanelGender2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGender2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGender2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelGender2Layout.createSequentialGroup()
                        .addComponent(lblOtherSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelGender2Layout.setVerticalGroup(
            jPanelGender2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGender2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblGender3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOtherSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(414, 414, 414)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnAssignToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnPres, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAssignToDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnReportBacktoAM, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnBed, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(jPanelGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jPanelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jPanelGender2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 31, Short.MAX_VALUE))
                                .addComponent(doctorJpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 36, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelGender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelGender2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAssignToDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReportBacktoAM, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAssignToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(doctorJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RegisteredUser user = request.getUser();
        UserReport userReport = new UserReport(userProcessContainer, system, user);
        userProcessContainer.add("userReport", userReport);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void toggleButton() {
        if (buttonFlag.equalsIgnoreCase("patManAllReq")) {
            btnAssignToDoctor.setVisible(false);
            btnReportBacktoAM.setVisible(false);
            btnViewPresc.setVisible(false);
            viewAvailableTest.setVisible(false);
        } else if (buttonFlag.equalsIgnoreCase("patManAssignedReq")) {
            btnAssignToMe.setVisible(false);
            btnReportBacktoAM.setVisible(false);
            btnViewPresc.setVisible(false);
            viewAvailableTest.setVisible(false);

        } else if (buttonFlag.equalsIgnoreCase("doctor")) {
            btnAssignToDoctor.setVisible(false);
            btnAssignToMe.setVisible(false);
            btnPres.setVisible(true);
            btnBed.setVisible(true);
            btnTest.setVisible(true);
        } else if (buttonFlag.equalsIgnoreCase("hospital")) {
            btnAssignToDoctor.setVisible(false);
            btnAssignToMe.setVisible(false);
            btnPres.setVisible(false);
            btnBed.setVisible(false);
            btnTest.setVisible(false);
            doctorJpanel.setVisible(false);
            btnReportBacktoAM.setVisible(false);
        }
    }
    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:

        if (request.getPatientManager() == null) {
            request.setPatientManager(patientManager);
            request.setStatus("Assigned to Patient Manager" + patientManager.getName());
            patientManager.getRequestDirectory().addRequestList(request);
            populateprofile();
            JOptionPane.showMessageDialog(null, "This Request has been assigned to you successfuuly");

        } else {
            JOptionPane.showMessageDialog(null, "This Request is already assigned to: " + request.getPatientManager().getName());
        }


    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnAssignToDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToDoctorActionPerformed
        // TODO add your handling code here:
        doctorJpanel.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) doctorJTable.getModel();
        model.setRowCount(0);
        for (City city : system.getCityList()) {
            if (city.getName().equalsIgnoreCase(request.getUser().getRegisteredUserCity().getName())) {
                for (Enterprise ent : city.getEnterpriseDir().getEnterpriseList()) {
                    if (ent.getEnterpriseCategory().getValue().equalsIgnoreCase("Hospital")) {
                        for (Organization org : ent.getOrganizationDirectory().getOrgList()) {
                            if (org.getOrgType().getValue().equalsIgnoreCase("Doctor Organization")) {
                                for (Doctor doc : org.getDocDir().getdoctorDirectory()) {
                                    Object[] row = new Object[4];
                                    row[0] = doc;
                                    row[1] = doc.getDegree();
                                    row[2] = doc.getYearsExperience();
                                    row[3] = doc.getZipcode();
                                    model.addRow(row);

                                }

                            }

                        }
                    }
                }
            }
        }


    }//GEN-LAST:event_btnAssignToDoctorActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctorJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!");
            return;
        } else {
            if (request.getDoctor() == null) {
                Doctor doc = (Doctor) doctorJTable.getValueAt(selectedRow, 0);
                request.setStatus("Assigned to doctor-" + doc.getName());
                request.setDoctor(doc);
                doc.getRequestDirectory().addRequestList(request);
                populateprofile();
                JOptionPane.showMessageDialog(null, "This request assigned to doctor " + doc.getName() + " Successfully!");
                doctorJpanel.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "This request is already assigned to doctor " + request.getDoctor().getName());
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBedActionPerformed
        // TODO add your handling code here:
        AssignHospitalToRequest assignHospital = new AssignHospitalToRequest(userProcessContainer, enterprise, useraccount, system, request, org);
        userProcessContainer.add("userReport", assignHospital);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBedActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
         HealthRequestReportTest healthRequestReportTest=new HealthRequestReportTest(userProcessContainer,enterprise,useraccount,system, request, null, org);
         userProcessContainer.add("PatientManagerProfileJPanel", healthRequestReportTest);
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer);
    }//GEN-LAST:event_btnTestActionPerformed

    private void btnPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresActionPerformed
        AddPrescription addPrescription = new AddPrescription(userProcessContainer, enterprise, useraccount, system, request);
        userProcessContainer.add("PatientManagerProfileJPanel", addPrescription);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPresActionPerformed

    private void btnReportBacktoAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportBacktoAMActionPerformed
        // TODO add your handling code here:
        PatientManager patMan = request.getPatientManager();
        Date date = new Date();
        String nowDtae = formatter.format(date);
        PersonalNotification notification = new PersonalNotification(
                "Doctor has assigned this request back to you", nowDtae, request);
        notification.setStatus("new");
        patMan.getNotificationDirectory().addNotification(notification);
        request.setStatus("quarantined");
        populateprofile();
        JOptionPane.showMessageDialog(null, "This patient has been marked as quarantined ");
        toggleBTAMButtons();
    }//GEN-LAST:event_btnReportBacktoAMActionPerformed

    private void btnViewPrescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPrescActionPerformed
        // TODO add your handling code here:
        ViewPrescriptionJPanel  viewPrescription=new ViewPrescriptionJPanel(userProcessContainer,enterprise,useraccount,system,request,org);
        userProcessContainer.add("viewPrescriptionPanel", viewPrescription);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewPrescActionPerformed

    private void viewAvailableTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAvailableTestActionPerformed
        // TODO add your handling code here:
        CompletedTestReport completedTestResult=new CompletedTestReport(userProcessContainer,enterprise,useraccount,system, request);
        userProcessContainer.add("userReport", completedTestResult);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewAvailableTestActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBackground(new java.awt.Color(253, 135, 124));
        jButton2.setContentAreaFilled(true);
        jButton2.setFocusPainted(true);
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(true);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setBorderPainted(true);
    }//GEN-LAST:event_jButton2MouseExited

    private void viewAvailableTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAvailableTestMouseEntered
        // TODO add your handling code here:
        viewAvailableTest.setBackground(new java.awt.Color(253, 135, 124));
        viewAvailableTest.setContentAreaFilled(true);
        viewAvailableTest.setFocusPainted(true);
        viewAvailableTest.setBorderPainted(false);
        viewAvailableTest.setOpaque(true);
    }//GEN-LAST:event_viewAvailableTestMouseEntered

    private void viewAvailableTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAvailableTestMouseExited
        // TODO add your handling code here:
        viewAvailableTest.setContentAreaFilled(false);
        viewAvailableTest.setFocusPainted(false);
        viewAvailableTest.setBorderPainted(true);
    }//GEN-LAST:event_viewAvailableTestMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(253, 135, 124));
        jButton1.setContentAreaFilled(true);
        jButton1.setFocusPainted(true);
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(true);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setBorderPainted(true);
    }//GEN-LAST:event_jButton1MouseExited

    private void btnAssignToMeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignToMeMouseEntered
        // TODO add your handling code here:
        btnAssignToMe.setBackground(new java.awt.Color(253, 135, 124));
        btnAssignToMe.setContentAreaFilled(true);
        btnAssignToMe.setFocusPainted(true);
        btnAssignToMe.setBorderPainted(false);
        btnAssignToMe.setOpaque(true);
    }//GEN-LAST:event_btnAssignToMeMouseEntered

    private void btnAssignToMeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignToMeMouseExited
        // TODO add your handling code here:
        btnAssignToMe.setContentAreaFilled(false);
        btnAssignToMe.setFocusPainted(false);
        btnAssignToMe.setBorderPainted(true);
    }//GEN-LAST:event_btnAssignToMeMouseExited

    private void btnAssignToDoctorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignToDoctorMouseEntered
        // TODO add your handling code here:
        btnAssignToDoctor.setBackground(new java.awt.Color(253, 135, 124));
        btnAssignToDoctor.setContentAreaFilled(true);
        btnAssignToDoctor.setFocusPainted(true);
        btnAssignToDoctor.setBorderPainted(false);
        btnAssignToDoctor.setOpaque(true);
    }//GEN-LAST:event_btnAssignToDoctorMouseEntered

    private void btnAssignToDoctorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignToDoctorMouseExited
        // TODO add your handling code here:
        btnAssignToDoctor.setContentAreaFilled(false);
        btnAssignToDoctor.setFocusPainted(false);
        btnAssignToDoctor.setBorderPainted(true);
    }//GEN-LAST:event_btnAssignToDoctorMouseExited

    private void btnReportBacktoAMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportBacktoAMMouseEntered
        // TODO add your handling code here:
        btnReportBacktoAM.setBackground(new java.awt.Color(253, 135, 124));
        btnReportBacktoAM.setContentAreaFilled(true);
        btnReportBacktoAM.setFocusPainted(true);
        btnReportBacktoAM.setBorderPainted(false);
        btnReportBacktoAM.setOpaque(true);
    }//GEN-LAST:event_btnReportBacktoAMMouseEntered

    private void btnReportBacktoAMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportBacktoAMMouseExited
        // TODO add your handling code here:
        btnReportBacktoAM.setContentAreaFilled(false);
        btnReportBacktoAM.setFocusPainted(false);
        btnReportBacktoAM.setBorderPainted(true);
    }//GEN-LAST:event_btnReportBacktoAMMouseExited

    private void btnPresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPresMouseEntered
        // TODO add your handling code here:
        btnPres.setBackground(new java.awt.Color(253, 135, 124));
        btnPres.setContentAreaFilled(true);
        btnPres.setFocusPainted(true);
        btnPres.setBorderPainted(false);
        btnPres.setOpaque(true);
    }//GEN-LAST:event_btnPresMouseEntered

    private void btnPresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPresMouseExited
        // TODO add your handling code here:
        btnPres.setContentAreaFilled(false);
        btnPres.setFocusPainted(false);
        btnPres.setBorderPainted(true);
    }//GEN-LAST:event_btnPresMouseExited

    private void btnBedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBedMouseEntered
        // TODO add your handling code here:
        btnBed.setBackground(new java.awt.Color(253, 135, 124));
        btnBed.setContentAreaFilled(true);
        btnBed.setFocusPainted(true);
        btnBed.setBorderPainted(false);
        btnBed.setOpaque(true);
    }//GEN-LAST:event_btnBedMouseEntered

    private void btnBedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBedMouseExited
        // TODO add your handling code here:
        btnBed.setContentAreaFilled(false);
        btnBed.setFocusPainted(false);
        btnBed.setBorderPainted(true);
    }//GEN-LAST:event_btnBedMouseExited

    private void btnTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTestMouseEntered
        // TODO add your handling code here
        btnTest.setBackground(new java.awt.Color(253, 135, 124));
        btnTest.setContentAreaFilled(true);
        btnTest.setFocusPainted(true);
        btnTest.setBorderPainted(false);
        btnTest.setOpaque(true);
    }//GEN-LAST:event_btnTestMouseEntered

    private void btnTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTestMouseExited
        // TODO add your handling code here:
        btnTest.setContentAreaFilled(false);
        btnTest.setFocusPainted(false);
        btnTest.setBorderPainted(true);
    }//GEN-LAST:event_btnTestMouseExited

    private void btnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseEntered
        // TODO add your handling code here:
        btnSubmit.setBackground(new java.awt.Color(253, 135, 124));
        btnSubmit.setContentAreaFilled(true);
        btnSubmit.setFocusPainted(true);
        btnSubmit.setBorderPainted(false);
        btnSubmit.setOpaque(true);
    }//GEN-LAST:event_btnSubmitMouseEntered

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        // TODO add your handling code here:
        btnSubmit.setContentAreaFilled(false);
        btnSubmit.setFocusPainted(false);
        btnSubmit.setBorderPainted(true);
    }//GEN-LAST:event_btnSubmitMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToDoctor;
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnBed;
    private javax.swing.JButton btnPres;
    private javax.swing.JButton btnReportBacktoAM;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnViewPresc;
    private javax.swing.JTable doctorJTable;
    private javax.swing.JPanel doctorJpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelGender;
    private javax.swing.JPanel jPanelGender1;
    private javax.swing.JPanel jPanelGender2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBodyPain;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblContactNo1;
    private javax.swing.JLabel lblContactNo2;
    private javax.swing.JLabel lblContactNo3;
    private javax.swing.JLabel lblCough;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblDob1;
    private javax.swing.JLabel lblDoctorsName;
    private javax.swing.JLabel lblFever;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblGender2;
    private javax.swing.JLabel lblGender3;
    private javax.swing.JLabel lblHospitalsName;
    private javax.swing.JLabel lblNursesName;
    private javax.swing.JLabel lblOtherSymptoms;
    private javax.swing.JLabel lblPatientManagerName;
    private javax.swing.JLabel lblPatientsName;
    private javax.swing.JLabel lblRequestNumber;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JLabel lblZipCode1;
    private javax.swing.JButton viewAvailableTest;
    // End of variables declaration//GEN-END:variables

    private void populateprofile() {
        lblRequestNumber.setText(request.getRequestNumber());
        lblPatientsName.setText(request.getUser().getFullName());
        lblContact.setText(request.getUser().getContactNumber());
        lblGender.setText(request.getUser().getGender());
        lblDob.setText(request.getUser().getDob());
        lblPatientManagerName.setText(request.getPatientManager() == null ? "Not Assigned" : request.getPatientManager().getName());
        lblDoctorsName.setText(request.getDoctor() == null ? "Not Assigned" : request.getDoctor().getName());
        lblNursesName.setText(request.getNurse() == null ? "Not Assigned" : request.getNurse().getName());
        lblHospitalsName.setText(request.getHospital() == null ? "Not Assigned" : request.getHospital().getName());
        lblStatus.setText(request.getStatus());
        lblFever.setText(request.getFever());
        lblCough.setText(request.getCough());
        lblBodyPain.setText(request.getBodyPain());
        lblOtherSymptoms.setText(request.getOtherSymptoms());

    }

    private void toggleActionButtons() {
        if (request.getPatientManager() != null) {
            btnAssignToMe.setVisible(false);
        }
    }

//    private void togglePrescriptionButton(){
//        if(request.getPrescriptionDirectory().getPrescriptionList().isEmpty()){
//            btnViewPresc.setVisible(false);
//            btnReportBacktoAM.setVisible(false);
//        }
//    }
    private void toggleDoctorButton() {
        if (request.getDoctor() != null) {
            btnAssignToDoctor.setVisible(false);
        }
    }

    private void toggleAllButtons() {
        if (request.getStatus().equalsIgnoreCase("discharged") || request.getStatus().equalsIgnoreCase("Negative") || request.getHospital() != null) {
            btnAssignToDoctor.setVisible(false);
            btnAssignToMe.setVisible(false);
            btnBed.setVisible(false);
            btnReportBacktoAM.setVisible(false);
            btnTest.setVisible(false);
        }

    }

    private void toggleBTAMButtons() {
        if (request.getStatus().equalsIgnoreCase("quarantined")) {
            btnAssignToDoctor.setVisible(false);
            btnAssignToMe.setVisible(false);
            btnReportBacktoAM.setVisible(false);
        }

    }
}
