/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.UserRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author jazibjavaid
 */

public class UserWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalEntAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount useraccount;
    Organization org;
    EcoSystem system;
    public UserWorkAreaJPanel(JPanel userProcessContainer, UserAccount useraccount, Organization org, Enterprise enterprise, EcoSystem system) {
        
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.useraccount=useraccount;
        this.org=org;
        this.system=system;
        
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(253,135,124));
    }
    
    void resetColor(JPanel panel){
         panel.setBackground(new Color(253,218,207));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnProfile_Panel = new javax.swing.JPanel();
        btnProfile = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCosultDoc_JPanel = new javax.swing.JPanel();
        btnConsultDoc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAmbulance_JPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnAmbulance = new javax.swing.JLabel();
        workAreaJPanel = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(253, 218, 207));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProfile_Panel.setBackground(new java.awt.Color(253, 135, 124));
        btnProfile_Panel.setToolTipText("");

        btnProfile.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProfile.setText("Manage Profile");
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProfileMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/userp.png"))); // NOI18N

        javax.swing.GroupLayout btnProfile_PanelLayout = new javax.swing.GroupLayout(btnProfile_Panel);
        btnProfile_Panel.setLayout(btnProfile_PanelLayout);
        btnProfile_PanelLayout.setHorizontalGroup(
            btnProfile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProfile_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        btnProfile_PanelLayout.setVerticalGroup(
            btnProfile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProfile_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnProfile_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 40));

        btnCosultDoc_JPanel.setBackground(new java.awt.Color(253, 218, 207));
        btnCosultDoc_JPanel.setToolTipText("");
        btnCosultDoc_JPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCosultDoc_JPanelMousePressed(evt);
            }
        });

        btnConsultDoc.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnConsultDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConsultDoc.setText("Consult Doctor");
        btnConsultDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConsultDocMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/doc1.png"))); // NOI18N

        javax.swing.GroupLayout btnCosultDoc_JPanelLayout = new javax.swing.GroupLayout(btnCosultDoc_JPanel);
        btnCosultDoc_JPanel.setLayout(btnCosultDoc_JPanelLayout);
        btnCosultDoc_JPanelLayout.setHorizontalGroup(
            btnCosultDoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCosultDoc_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        btnCosultDoc_JPanelLayout.setVerticalGroup(
            btnCosultDoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCosultDoc_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnCosultDoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(btnCosultDoc_JPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 40));

        btnAmbulance_JPanel.setBackground(new java.awt.Color(253, 218, 207));
        btnAmbulance_JPanel.setToolTipText("");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/ambulance.png"))); // NOI18N

        btnAmbulance.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnAmbulance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAmbulance.setText("Book Ambulance");
        btnAmbulance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAmbulanceMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnAmbulance_JPanelLayout = new javax.swing.GroupLayout(btnAmbulance_JPanel);
        btnAmbulance_JPanel.setLayout(btnAmbulance_JPanelLayout);
        btnAmbulance_JPanelLayout.setHorizontalGroup(
            btnAmbulance_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAmbulance_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        btnAmbulance_JPanelLayout.setVerticalGroup(
            btnAmbulance_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAmbulance_JPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(btnAmbulance_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnAmbulance_JPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 880));

        workAreaJPanel.setBackground(new java.awt.Color(255, 255, 255));
        workAreaJPanel.setLayout(new java.awt.CardLayout());
        add(workAreaJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1180, 880));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMousePressed
        // TODO add your handling code here:
        setColor(btnProfile_Panel);

        resetColor(btnAmbulance_JPanel);

        resetColor(btnCosultDoc_JPanel);
        
    }//GEN-LAST:event_btnProfileMousePressed

    private void btnConsultDocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultDocMousePressed
        // TODO add your handling code here:
        setColor(btnCosultDoc_JPanel);
 
        resetColor(btnAmbulance_JPanel);

        resetColor(btnProfile_Panel);
        
        
    }//GEN-LAST:event_btnConsultDocMousePressed

    private void btnAmbulanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAmbulanceMousePressed
        // TODO add your handling code here:
        setColor(btnAmbulance_JPanel);
       
        resetColor(btnCosultDoc_JPanel);
     
        resetColor(btnProfile_Panel);
        
    }//GEN-LAST:event_btnAmbulanceMousePressed

    private void btnCosultDoc_JPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCosultDoc_JPanelMousePressed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_btnCosultDoc_JPanelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAmbulance;
    private javax.swing.JPanel btnAmbulance_JPanel;
    private javax.swing.JLabel btnConsultDoc;
    private javax.swing.JPanel btnCosultDoc_JPanel;
    private javax.swing.JLabel btnProfile;
    private javax.swing.JPanel btnProfile_Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel workAreaJPanel;
    // End of variables declaration//GEN-END:variables
}
