/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.UserRole;

import Business.EcoSystem;
import Business.RegisteredUser.RegisteredUser;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author jazibjavaid
 */
public class UserReport extends javax.swing.JPanel {

    /**
     * Creates new form UserReport
     */
    private String selectedValue;
    private EcoSystem ecosystem;
    private RegisteredUser user;
    JPanel userProcessContainer;

    public UserReport(JPanel userProcessContainer, EcoSystem ecosystem, RegisteredUser user) {
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.user = user;
        initComponents();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLeft1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblDob3 = new javax.swing.JLabel();
        txtBloodGroup = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtHeight = new javax.swing.JLabel();
        lblDob4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtWeight = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblProfilePicture = new javax.swing.JLabel();
        jPanelMobileNumber = new javax.swing.JPanel();
        txtMobileNumber = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        jPanelSsn = new javax.swing.JPanel();
        txtEmail = new javax.swing.JLabel();
        lblSsn1 = new javax.swing.JLabel();
        jPanellbAddress = new javax.swing.JPanel();
        txtAddress = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jPanelFoodPreference = new javax.swing.JPanel();
        txtFoodPreference = new javax.swing.JLabel();
        lblFoodPreference = new javax.swing.JLabel();
        txtUserFullName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDob = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JLabel();
        jPanelGender = new javax.swing.JPanel();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanelAlcoholConsumption2 = new javax.swing.JPanel();
        lblAlcoholConsumption2 = new javax.swing.JLabel();
        txtIsVaccinated = new javax.swing.JLabel();
        jPanelAlcoholConsumption3 = new javax.swing.JPanel();
        lblAlcoholConsumption3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaAllergies = new javax.swing.JTextArea();
        jPanelAlcoholConsumption4 = new javax.swing.JPanel();
        lblAlcoholConsumption4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaSurgeries = new javax.swing.JTextArea();
        lblHealthProfile = new javax.swing.JLabel();
        lblHealthProfile1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1535, 733));

        jPanelLeft1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lblDob3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblDob3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDob3.setText("Blood Group");

        txtBloodGroup.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtBloodGroup.setForeground(new java.awt.Color(51, 51, 51));
        txtBloodGroup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBloodGroup.setText("-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDob3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(txtBloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDob3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        txtHeight.setBackground(new java.awt.Color(255, 255, 255));
        txtHeight.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtHeight.setForeground(new java.awt.Color(51, 51, 51));
        txtHeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHeight.setText("-");

        lblDob4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblDob4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDob4.setText("Height (cms)");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDob4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDob4)
                .addGap(10, 10, 10))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        txtWeight.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtWeight.setForeground(new java.awt.Color(51, 51, 51));
        txtWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtWeight.setText("-");

        lblWeight.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWeight.setText("Weight (kg)");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(lblWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWeight)
                .addGap(10, 10, 10))
        );

        lblProfilePicture.setBackground(new java.awt.Color(204, 204, 204));
        lblProfilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/userbig.png"))); // NOI18N
        lblProfilePicture.setMaximumSize(new java.awt.Dimension(120, 120));
        lblProfilePicture.setMinimumSize(new java.awt.Dimension(120, 120));

        jPanelMobileNumber.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMobileNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtMobileNumber.setForeground(new java.awt.Color(51, 51, 51));
        txtMobileNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblSsn.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblSsn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSsn.setText("Mobile Number");
        lblSsn.setIconTextGap(10);

        javax.swing.GroupLayout jPanelMobileNumberLayout = new javax.swing.GroupLayout(jPanelMobileNumber);
        jPanelMobileNumber.setLayout(jPanelMobileNumberLayout);
        jPanelMobileNumberLayout.setHorizontalGroup(
            jPanelMobileNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMobileNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMobileNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMobileNumberLayout.setVerticalGroup(
            jPanelMobileNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMobileNumberLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanelSsn.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSsn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        txtEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblSsn1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblSsn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSsn1.setText("E-mail Id");
        lblSsn1.setIconTextGap(10);

        javax.swing.GroupLayout jPanelSsnLayout = new javax.swing.GroupLayout(jPanelSsn);
        jPanelSsn.setLayout(jPanelSsnLayout);
        jPanelSsnLayout.setHorizontalGroup(
            jPanelSsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSsnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSsn1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSsnLayout.setVerticalGroup(
            jPanelSsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSsnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSsn1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanellbAddress.setBackground(new java.awt.Color(255, 255, 255));
        jPanellbAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtAddress.setForeground(new java.awt.Color(51, 51, 51));
        txtAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAddress.setText("Address");
        lblAddress.setIconTextGap(10);

        javax.swing.GroupLayout jPanellbAddressLayout = new javax.swing.GroupLayout(jPanellbAddress);
        jPanellbAddress.setLayout(jPanellbAddressLayout);
        jPanellbAddressLayout.setHorizontalGroup(
            jPanellbAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellbAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanellbAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanellbAddressLayout.setVerticalGroup(
            jPanellbAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanellbAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFoodPreference.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFoodPreference.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtFoodPreference.setForeground(new java.awt.Color(51, 51, 51));
        txtFoodPreference.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtFoodPreference.setText("NA");

        lblFoodPreference.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblFoodPreference.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFoodPreference.setText("Food Preference");
        lblFoodPreference.setIconTextGap(10);

        javax.swing.GroupLayout jPanelFoodPreferenceLayout = new javax.swing.GroupLayout(jPanelFoodPreference);
        jPanelFoodPreference.setLayout(jPanelFoodPreferenceLayout);
        jPanelFoodPreferenceLayout.setHorizontalGroup(
            jPanelFoodPreferenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFoodPreferenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFoodPreference, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFoodPreferenceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFoodPreference, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelFoodPreferenceLayout.setVerticalGroup(
            jPanelFoodPreferenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFoodPreferenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoodPreference, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFoodPreference, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtUserFullName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtUserFullName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUserFullName.setText("NA");

        javax.swing.GroupLayout jPanelLeft1Layout = new javax.swing.GroupLayout(jPanelLeft1);
        jPanelLeft1.setLayout(jPanelLeft1Layout);
        jPanelLeft1Layout.setHorizontalGroup(
            jPanelLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeft1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelLeft1Layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtUserFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanellbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFoodPreference, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeft1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanelLeft1Layout.setVerticalGroup(
            jPanelLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeft1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtUserFullName)
                .addGap(20, 20, 20)
                .addGroup(jPanelLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanellbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanelFoodPreference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(177, 80));

        lblDob.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblDob.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDob.setText("Birthday");

        txtDateOfBirth.setForeground(new java.awt.Color(51, 51, 51));
        txtDateOfBirth.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblDob, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblDob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelGender.setBackground(new java.awt.Color(204, 204, 204));
        jPanelGender.setPreferredSize(new java.awt.Dimension(177, 80));

        lblGender.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender.setText("Gender");

        txtGender.setForeground(new java.awt.Color(51, 51, 51));
        txtGender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtGender.setText("NA");

        javax.swing.GroupLayout jPanelGenderLayout = new javax.swing.GroupLayout(jPanelGender);
        jPanelGender.setLayout(jPanelGenderLayout);
        jPanelGenderLayout.setHorizontalGroup(
            jPanelGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGenderLayout.createSequentialGroup()
                .addGroup(jPanelGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGenderLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGenderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelGenderLayout.setVerticalGroup(
            jPanelGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGenderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblGender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        btnBack.setBackground(new java.awt.Color(253, 135, 124));
        btnBack.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.setToolTipText("");
        btnBack.setActionCommand("University");
        btnBack.setAlignmentY(0.0F);
        btnBack.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBack.setContentAreaFilled(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBack.setIconTextGap(10);
        btnBack.setMargin(new java.awt.Insets(10, 5, 0, 2));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanelAlcoholConsumption2.setBackground(new java.awt.Color(204, 204, 204));
        jPanelAlcoholConsumption2.setPreferredSize(new java.awt.Dimension(177, 80));

        lblAlcoholConsumption2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblAlcoholConsumption2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAlcoholConsumption2.setText("Covid Vaccinated");

        txtIsVaccinated.setForeground(new java.awt.Color(51, 51, 51));
        txtIsVaccinated.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtIsVaccinated.setText("NA");

        javax.swing.GroupLayout jPanelAlcoholConsumption2Layout = new javax.swing.GroupLayout(jPanelAlcoholConsumption2);
        jPanelAlcoholConsumption2.setLayout(jPanelAlcoholConsumption2Layout);
        jPanelAlcoholConsumption2Layout.setHorizontalGroup(
            jPanelAlcoholConsumption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlcoholConsumption2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelAlcoholConsumption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIsVaccinated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAlcoholConsumption2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAlcoholConsumption2Layout.setVerticalGroup(
            jPanelAlcoholConsumption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlcoholConsumption2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblAlcoholConsumption2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIsVaccinated, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAlcoholConsumption3.setBackground(new java.awt.Color(204, 204, 204));
        jPanelAlcoholConsumption3.setPreferredSize(new java.awt.Dimension(177, 80));

        lblAlcoholConsumption3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblAlcoholConsumption3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAlcoholConsumption3.setText("Allergies");

        txtAreaAllergies.setColumns(20);
        txtAreaAllergies.setRows(5);
        jScrollPane2.setViewportView(txtAreaAllergies);

        javax.swing.GroupLayout jPanelAlcoholConsumption3Layout = new javax.swing.GroupLayout(jPanelAlcoholConsumption3);
        jPanelAlcoholConsumption3.setLayout(jPanelAlcoholConsumption3Layout);
        jPanelAlcoholConsumption3Layout.setHorizontalGroup(
            jPanelAlcoholConsumption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlcoholConsumption3Layout.createSequentialGroup()
                .addGroup(jPanelAlcoholConsumption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlcoholConsumption3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblAlcoholConsumption3, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(jPanelAlcoholConsumption3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAlcoholConsumption3Layout.setVerticalGroup(
            jPanelAlcoholConsumption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlcoholConsumption3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblAlcoholConsumption3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanelAlcoholConsumption4.setBackground(new java.awt.Color(204, 204, 204));
        jPanelAlcoholConsumption4.setPreferredSize(new java.awt.Dimension(177, 80));

        lblAlcoholConsumption4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblAlcoholConsumption4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAlcoholConsumption4.setText("    Surgeries");

        txtAreaSurgeries.setColumns(20);
        txtAreaSurgeries.setRows(5);
        jScrollPane3.setViewportView(txtAreaSurgeries);

        javax.swing.GroupLayout jPanelAlcoholConsumption4Layout = new javax.swing.GroupLayout(jPanelAlcoholConsumption4);
        jPanelAlcoholConsumption4.setLayout(jPanelAlcoholConsumption4Layout);
        jPanelAlcoholConsumption4Layout.setHorizontalGroup(
            jPanelAlcoholConsumption4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlcoholConsumption4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblAlcoholConsumption4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );
        jPanelAlcoholConsumption4Layout.setVerticalGroup(
            jPanelAlcoholConsumption4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlcoholConsumption4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblAlcoholConsumption4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jPanelAlcoholConsumption3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAlcoholConsumption4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAlcoholConsumption2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAlcoholConsumption2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanelAlcoholConsumption4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelAlcoholConsumption3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        lblHealthProfile.setBackground(new java.awt.Color(244, 249, 249));
        lblHealthProfile.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblHealthProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHealthProfile.setText("Patient Details");

        lblHealthProfile1.setBackground(new java.awt.Color(255, 255, 255));
        lblHealthProfile1.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblHealthProfile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHealthProfile1.setText("Medical Conditions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelLeft1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(423, 423, 423))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jPanelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lblHealthProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(lblHealthProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHealthProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblHealthProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelLeft1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // back btn logic
        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setBackground(new java.awt.Color(253,135,124));
        btnBack.setContentAreaFilled(true);
        btnBack.setFocusPainted(true);
        btnBack.setBorderPainted(false);
        btnBack.setOpaque(true);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusPainted(false);
        btnBack.setBorderPainted(true);
    }//GEN-LAST:event_btnBackMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAlcoholConsumption2;
    private javax.swing.JPanel jPanelAlcoholConsumption3;
    private javax.swing.JPanel jPanelAlcoholConsumption4;
    private javax.swing.JPanel jPanelFoodPreference;
    private javax.swing.JPanel jPanelGender;
    private javax.swing.JPanel jPanelLeft1;
    private javax.swing.JPanel jPanelMobileNumber;
    private javax.swing.JPanel jPanelSsn;
    private javax.swing.JPanel jPanellbAddress;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAlcoholConsumption2;
    private javax.swing.JLabel lblAlcoholConsumption3;
    private javax.swing.JLabel lblAlcoholConsumption4;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblDob3;
    private javax.swing.JLabel lblDob4;
    private javax.swing.JLabel lblFoodPreference;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHealthProfile;
    private javax.swing.JLabel lblHealthProfile1;
    private javax.swing.JLabel lblProfilePicture;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblSsn1;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JTextArea txtAreaAllergies;
    private javax.swing.JTextArea txtAreaSurgeries;
    private javax.swing.JLabel txtBloodGroup;
    private javax.swing.JLabel txtDateOfBirth;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFoodPreference;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtHeight;
    private javax.swing.JLabel txtIsVaccinated;
    private javax.swing.JLabel txtMobileNumber;
    private javax.swing.JLabel txtUserFullName;
    private javax.swing.JLabel txtWeight;
    // End of variables declaration//GEN-END:variables

    private void backAction() {
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }

    private void setData() {

        txtUserFullName.setText(user.getName());
        txtMobileNumber.setText(user.getContactNumber());
        txtAddress.setText(user.getAddress());
        txtEmail.setText(user.getEmail());
        txtBloodGroup.setText(user.getBloodGroup());
        txtHeight.setText(user.getHeight());
        txtWeight.setText(user.getWeight());
        txtFoodPreference.setText(user.getFoodpreference());
        txtDateOfBirth.setText(user.getDob());
        txtGender.setText(user.getGender());
        txtIsVaccinated.setText(user.getIsVaccinated());
        txtAreaAllergies.setText(user.getAllergies());
        txtAreaSurgeries.setText(user.getSurgeries());
    }
}
