/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HospitalEntAdminRole;

import UI.UserRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.Organization;
import Business.PatientAdvisor.PatientManager;
import Business.RegisteredUser.RegisteredUser;
import Business.UserAccount.UserAccount;
import Business.WorkProcess.HealthRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shantanutyagi
 */
public class PatientsRequestReport extends javax.swing.JPanel {

    /**
     * Creates new form ManageProfileJPanel
     */
    private ArrayList<String> comorbid;
    private UserAccount useraccount;
    private EcoSystem system;
    private HealthRequest request;
    private JPanel userProcessContainer;
    private PatientManager patientManager;
    private Enterprise enterprise;
    private HospitalEnterprise hospEnt;
    private Organization org;
    DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");

    public PatientsRequestReport(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, EcoSystem system, HealthRequest request, PatientManager patientManager, Organization org) {
        initComponents();
        this.useraccount = account;
        this.system = system;
        this.request = request;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.patientManager = patientManager;
        this.org = org;
        populateprofile();
        getEnterprise();
        this.comorbid = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        lblContactNo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblContactNo1 = new javax.swing.JLabel();
        lblRequestNumber = new javax.swing.JLabel();
        lblPatientsName = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblPatientManagerName = new javax.swing.JLabel();
        lblZipCode1 = new javax.swing.JLabel();
        lblDoctorsName = new javax.swing.JLabel();
        lblContactNo2 = new javax.swing.JLabel();
        lblNursesName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblHospitalsName = new javax.swing.JLabel();
        lblContactNo3 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnTest = new javax.swing.JButton();
        btnDischarged = new javax.swing.JButton();
        btnCritical = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblDob1 = new javax.swing.JLabel();
        lblFever = new javax.swing.JLabel();
        jPanelGender1 = new javax.swing.JPanel();
        lblGender2 = new javax.swing.JLabel();
        lblCough = new javax.swing.JLabel();
        jPanelGender = new javax.swing.JPanel();
        lblGender1 = new javax.swing.JLabel();
        lblBodyPain = new javax.swing.JLabel();
        jPanelGender2 = new javax.swing.JPanel();
        lblGender3 = new javax.swing.JLabel();
        lblOtherSymptoms = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Request Number:");

        lblZipCode.setText("Patients Name:");

        lblContactNo.setText("Contact Number:");

        jLabel1.setText("Gender:");

        lblContactNo1.setText("Date of Birth");

        lblRequestNumber.setText("jLabel4");
        lblRequestNumber.setMaximumSize(new java.awt.Dimension(6, 20));
        lblRequestNumber.setMinimumSize(new java.awt.Dimension(6, 20));
        lblRequestNumber.setPreferredSize(new java.awt.Dimension(6, 20));

        lblPatientsName.setText("jLabel4");
        lblPatientsName.setMaximumSize(new java.awt.Dimension(6, 20));
        lblPatientsName.setMinimumSize(new java.awt.Dimension(6, 20));
        lblPatientsName.setPreferredSize(new java.awt.Dimension(6, 20));

        lblContact.setText("jLabel4");
        lblContact.setMaximumSize(new java.awt.Dimension(6, 20));
        lblContact.setMinimumSize(new java.awt.Dimension(6, 20));
        lblContact.setPreferredSize(new java.awt.Dimension(6, 20));

        lblGender.setText("jLabel4");
        lblGender.setMaximumSize(new java.awt.Dimension(6, 20));
        lblGender.setMinimumSize(new java.awt.Dimension(6, 20));
        lblGender.setPreferredSize(new java.awt.Dimension(6, 20));

        lblDob.setText("jLabel4");
        lblDob.setMaximumSize(new java.awt.Dimension(6, 20));
        lblDob.setMinimumSize(new java.awt.Dimension(6, 20));
        lblDob.setPreferredSize(new java.awt.Dimension(6, 20));

        jButton1.setBackground(new java.awt.Color(253, 135, 124));
        jButton1.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        jButton1.setText("View complete Profile");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Patient Manager Name:");

        lblPatientManagerName.setText("jLabel4");
        lblPatientManagerName.setMaximumSize(new java.awt.Dimension(6, 20));
        lblPatientManagerName.setMinimumSize(new java.awt.Dimension(6, 20));
        lblPatientManagerName.setPreferredSize(new java.awt.Dimension(6, 20));

        lblZipCode1.setText("Doctor's Name:");

        lblDoctorsName.setText("jLabel4");
        lblDoctorsName.setMaximumSize(new java.awt.Dimension(6, 20));
        lblDoctorsName.setMinimumSize(new java.awt.Dimension(6, 20));
        lblDoctorsName.setPreferredSize(new java.awt.Dimension(6, 20));

        lblContactNo2.setText("Nurse's Name:");

        lblNursesName.setText("jLabel4");
        lblNursesName.setMaximumSize(new java.awt.Dimension(6, 20));
        lblNursesName.setMinimumSize(new java.awt.Dimension(6, 20));
        lblNursesName.setPreferredSize(new java.awt.Dimension(6, 20));

        jLabel4.setText("Hospital's Name");

        lblHospitalsName.setText("jLabel4");
        lblHospitalsName.setMaximumSize(new java.awt.Dimension(6, 20));
        lblHospitalsName.setMinimumSize(new java.awt.Dimension(6, 20));
        lblHospitalsName.setPreferredSize(new java.awt.Dimension(6, 20));

        lblContactNo3.setText("Status");

        lblStatus.setText("jLabel4");
        lblStatus.setMaximumSize(new java.awt.Dimension(6, 20));
        lblStatus.setMinimumSize(new java.awt.Dimension(6, 20));
        lblStatus.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblContactNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblContactNo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblZipCode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblPatientManagerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDoctorsName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNursesName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblHospitalsName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblContactNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRequestNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPatientsName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblContact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRequestNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientsName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContact, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPatientManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDoctorsName, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(lblZipCode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNursesName, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(lblContactNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalsName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblContactNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        btnTest.setBackground(new java.awt.Color(253, 135, 124));
        btnTest.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnTest.setText("Assign Test");
        btnTest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTest.setContentAreaFilled(false);
        btnTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTestMouseExited(evt);
            }
        });
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        btnDischarged.setBackground(new java.awt.Color(253, 135, 124));
        btnDischarged.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnDischarged.setText("Mark Patient Discharged from Hospital");
        btnDischarged.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDischarged.setContentAreaFilled(false);
        btnDischarged.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDischargedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDischargedMouseExited(evt);
            }
        });
        btnDischarged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDischargedActionPerformed(evt);
            }
        });

        btnCritical.setBackground(new java.awt.Color(253, 135, 124));
        btnCritical.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnCritical.setText("Mark Critical");
        btnCritical.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCritical.setContentAreaFilled(false);
        btnCritical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCriticalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCriticalMouseExited(evt);
            }
        });
        btnCritical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriticalActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(177, 80));

        lblDob1.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblDob1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDob1.setText("Fever");

        lblFever.setBackground(new java.awt.Color(255, 255, 255));
        lblFever.setText("jLabel4");
        lblFever.setMaximumSize(new java.awt.Dimension(6, 20));
        lblFever.setMinimumSize(new java.awt.Dimension(6, 20));
        lblFever.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblDob1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFever, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblDob1)
                .addGap(18, 18, 18)
                .addComponent(lblFever, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanelGender1.setBackground(new java.awt.Color(204, 204, 204));
        jPanelGender1.setPreferredSize(new java.awt.Dimension(177, 80));

        lblGender2.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblGender2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender2.setText("Cough");

        lblCough.setBackground(new java.awt.Color(255, 255, 255));
        lblCough.setText("jLabel4");
        lblCough.setMaximumSize(new java.awt.Dimension(6, 20));
        lblCough.setMinimumSize(new java.awt.Dimension(6, 20));
        lblCough.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanelGender1Layout = new javax.swing.GroupLayout(jPanelGender1);
        jPanelGender1.setLayout(jPanelGender1Layout);
        jPanelGender1Layout.setHorizontalGroup(
            jPanelGender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGender1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(lblCough, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelGender1Layout.setVerticalGroup(
            jPanelGender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGender1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblGender2)
                .addGap(18, 18, 18)
                .addComponent(lblCough, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        jPanelGender.setBackground(new java.awt.Color(204, 204, 204));
        jPanelGender.setPreferredSize(new java.awt.Dimension(177, 80));

        lblGender1.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblGender1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender1.setText("Body Pain");

        lblBodyPain.setBackground(new java.awt.Color(255, 255, 255));
        lblBodyPain.setText("jLabel4");
        lblBodyPain.setMaximumSize(new java.awt.Dimension(6, 20));
        lblBodyPain.setMinimumSize(new java.awt.Dimension(6, 20));
        lblBodyPain.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanelGenderLayout = new javax.swing.GroupLayout(jPanelGender);
        jPanelGender.setLayout(jPanelGenderLayout);
        jPanelGenderLayout.setHorizontalGroup(
            jPanelGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGenderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(lblBodyPain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelGenderLayout.setVerticalGroup(
            jPanelGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGenderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblGender1)
                .addGap(18, 18, 18)
                .addComponent(lblBodyPain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        jPanelGender2.setBackground(new java.awt.Color(204, 204, 204));
        jPanelGender2.setPreferredSize(new java.awt.Dimension(177, 80));

        lblGender3.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        lblGender3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender3.setText("Other Symptoms");

        lblOtherSymptoms.setBackground(new java.awt.Color(255, 255, 255));
        lblOtherSymptoms.setText("jLabel4");
        lblOtherSymptoms.setMaximumSize(new java.awt.Dimension(6, 20));
        lblOtherSymptoms.setMinimumSize(new java.awt.Dimension(6, 20));
        lblOtherSymptoms.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanelGender2Layout = new javax.swing.GroupLayout(jPanelGender2);
        jPanelGender2.setLayout(jPanelGender2Layout);
        jPanelGender2Layout.setHorizontalGroup(
            jPanelGender2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGender2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGender2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelGender2Layout.createSequentialGroup()
                        .addComponent(lblOtherSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelGender2Layout.setVerticalGroup(
            jPanelGender2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGender2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblGender3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOtherSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanelGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelGender2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCritical, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnDischarged, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelGender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelGender2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCritical, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnDischarged, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RegisteredUser user = request.getUser();
        UserReport userReport = new UserReport(userProcessContainer, system, user);
        userProcessContainer.add("userReport", userReport);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDischargedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDischargedActionPerformed
        // TODO add your handling code here:
        if (request.getStatus().equalsIgnoreCase("Discharged")) {
            JOptionPane.showMessageDialog(null, "This Patient is already discharged from Hospital");
        } else {
            request.setStatus("Discharged");
            populateprofile();

            int bedCount = Integer.parseInt(hospEnt.getNumberOfBeds());
            bedCount = bedCount + 1;
            hospEnt.setNumberOfBeds(String.valueOf(bedCount));
        }

    }//GEN-LAST:event_btnDischargedActionPerformed

    private void btnCriticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriticalActionPerformed
        // TODO add your handling code here:
        if (request.getStatus().equalsIgnoreCase("Critical")) {
            JOptionPane.showMessageDialog(null, "This patient is already marked as critical");
        } else {
            request.setStatus("Critical");
            populateprofile();
        }
    }//GEN-LAST:event_btnCriticalActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        // TODO add your handling code here:
        HealthRequestReportTest healthRequestReportTest = new HealthRequestReportTest(userProcessContainer, enterprise, useraccount, system, request, null, org);
        userProcessContainer.add("PatientManagerProfileJPanel", healthRequestReportTest);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnTestActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(253, 135, 124));
        jButton1.setContentAreaFilled(true);
        jButton1.setFocusPainted(true);
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(true);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setBorderPainted(true);
    }//GEN-LAST:event_jButton1MouseExited

    private void btnTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTestMouseEntered
        // TODO add your handling code here:
        btnTest.setBackground(new java.awt.Color(253, 135, 124));
        btnTest.setContentAreaFilled(true);
        btnTest.setFocusPainted(true);
        btnTest.setBorderPainted(false);
        btnTest.setOpaque(true);
    }//GEN-LAST:event_btnTestMouseEntered

    private void btnTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTestMouseExited
        // TODO add your handling code here:
        btnTest.setContentAreaFilled(false);
        btnTest.setFocusPainted(false);
        btnTest.setBorderPainted(true);
    }//GEN-LAST:event_btnTestMouseExited

    private void btnCriticalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCriticalMouseEntered
        // TODO add your handling code here:
        btnCritical.setBackground(new java.awt.Color(253, 135, 124));
        btnCritical.setContentAreaFilled(true);
        btnCritical.setFocusPainted(true);
        btnCritical.setBorderPainted(false);
        btnCritical.setOpaque(true);
    }//GEN-LAST:event_btnCriticalMouseEntered

    private void btnCriticalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCriticalMouseExited
        // TODO add your handling code here:
        btnCritical.setContentAreaFilled(false);
        btnCritical.setFocusPainted(false);
        btnCritical.setBorderPainted(true);
    }//GEN-LAST:event_btnCriticalMouseExited

    private void btnDischargedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDischargedMouseEntered
        // TODO add your handling code here:
        btnDischarged.setBackground(new java.awt.Color(253, 135, 124));
        btnDischarged.setContentAreaFilled(true);
        btnDischarged.setFocusPainted(true);
        btnDischarged.setBorderPainted(false);
        btnDischarged.setOpaque(true);
    }//GEN-LAST:event_btnDischargedMouseEntered

    private void btnDischargedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDischargedMouseExited
        // TODO add your handling code here:
        btnDischarged.setContentAreaFilled(false);
        btnDischarged.setFocusPainted(false);
        btnDischarged.setBorderPainted(true);
    }//GEN-LAST:event_btnDischargedMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCritical;
    private javax.swing.JButton btnDischarged;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelGender;
    private javax.swing.JPanel jPanelGender1;
    private javax.swing.JPanel jPanelGender2;
    private javax.swing.JLabel lblBodyPain;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblContactNo1;
    private javax.swing.JLabel lblContactNo2;
    private javax.swing.JLabel lblContactNo3;
    private javax.swing.JLabel lblCough;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblDob1;
    private javax.swing.JLabel lblDoctorsName;
    private javax.swing.JLabel lblFever;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblGender2;
    private javax.swing.JLabel lblGender3;
    private javax.swing.JLabel lblHospitalsName;
    private javax.swing.JLabel lblNursesName;
    private javax.swing.JLabel lblOtherSymptoms;
    private javax.swing.JLabel lblPatientManagerName;
    private javax.swing.JLabel lblPatientsName;
    private javax.swing.JLabel lblRequestNumber;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JLabel lblZipCode1;
    // End of variables declaration//GEN-END:variables

    private void populateprofile() {
        lblRequestNumber.setText(request.getRequestNumber());
        lblPatientsName.setText(request.getUser().getFullName());
        lblContact.setText(request.getUser().getContactNumber());
        lblGender.setText(request.getUser().getGender());
        lblDob.setText(request.getUser().getDob());
        lblPatientManagerName.setText(request.getPatientManager() == null ? "Not Assigned" : request.getPatientManager().getName());
        lblDoctorsName.setText(request.getDoctor() == null ? "Not Assigned" : request.getDoctor().getName());
        lblNursesName.setText(request.getNurse() == null ? "Not Assigned" : request.getNurse().getName());
        lblHospitalsName.setText(request.getHospital() == null ? "Not Assigned" : request.getHospital().getName());
        lblStatus.setText(request.getStatus());
        lblFever.setText(request.getFever());
        lblCough.setText(request.getCough());
        lblBodyPain.setText(request.getBodyPain());
        lblOtherSymptoms.setText(request.getOtherSymptoms());

    }

    private void getEnterprise() {

        if (enterprise.getEnterpriseCategory().getValue().equalsIgnoreCase("Hospital")) {
            hospEnt = (HospitalEnterprise) enterprise;
        }
    }
}
